[project]
name = "libreoffice-python-docker"
version = "0.1.0"
description = "A Docker base image combining Python and LibreOffice for document processing"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"